//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhysicalPersonsDirectory.Common.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class RsStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RsStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PhysicalPersonsDirectory.Common.Resources.RsStrings", typeof(RsStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to პიროვნების დამატების დროს მოხდა გაუთვალისწინებელი შეცდომა.
        /// </summary>
        public static string AddPersonUnexpectedException {
            get {
                return ResourceManager.GetString("AddPersonUnexpectedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to დაკავშირებული პიროვნების დამატების დროს მოხდა გაუთვალისწინებელი შეცდომა.
        /// </summary>
        public static string AddRelatedPersonUnexpectedException {
            get {
                return ResourceManager.GetString("AddRelatedPersonUnexpectedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ბათუმი.
        /// </summary>
        public static string Batumi {
            get {
                return ResourceManager.GetString("Batumi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to კოლეგა.
        /// </summary>
        public static string Colleague {
            get {
                return ResourceManager.GetString("Colleague", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to პიროვნების წაშლის დროს მოხდა გაუთვალისწინებელი შეცდომა.
        /// </summary>
        public static string DeletePersonUnexpectedException {
            get {
                return ResourceManager.GetString("DeletePersonUnexpectedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to წასაშლელი კავშირი ფიზიკურ პირებს შორის ვერ მოიძებნა.
        /// </summary>
        public static string DeleteRelatedPersonNotFound {
            get {
                return ResourceManager.GetString("DeleteRelatedPersonNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to პიროვნების ცვლილების დროს მოხდა გაუთვალისწინებელი შეცდომა.
        /// </summary>
        public static string EditPersonUnexpectedException {
            get {
                return ResourceManager.GetString("EditPersonUnexpectedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ნაცნობი.
        /// </summary>
        public static string Familiar {
            get {
                return ResourceManager.GetString("Familiar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to მდედრობითი.
        /// </summary>
        public static string Female {
            get {
                return ResourceManager.GetString("Female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ფიზიკური პირის დეტალური ინფორმაციის მიღებოს დროს მოხდა გაუთვალისწინებელი შეცდომა.
        /// </summary>
        public static string GetPersonDetailsUnexpectedException {
            get {
                return ResourceManager.GetString("GetPersonDetailsUnexpectedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ფიზიკური პირების სიის მიღებოს დროს მოხდა გაუთვალისწინებელი შეცდომა.
        /// </summary>
        public static string GetPersonsUnexpectedException {
            get {
                return ResourceManager.GetString("GetPersonsUnexpectedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ფიზიკური პირების და მათთან დაკავშირებული ფიზიკური პირების სიის მიღებოს დროს მოხდა გაუთვალისწინებელი შეცდომა.
        /// </summary>
        public static string GetRelatedPersonsUnexpectedException {
            get {
                return ResourceManager.GetString("GetRelatedPersonsUnexpectedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to გორი.
        /// </summary>
        public static string Gori {
            get {
                return ResourceManager.GetString("Gori", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to სახლი.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ქუთაისი.
        /// </summary>
        public static string Kutaisi {
            get {
                return ResourceManager.GetString("Kutaisi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to მამრობითი.
        /// </summary>
        public static string Male {
            get {
                return ResourceManager.GetString("Male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to მობილური.
        /// </summary>
        public static string Mobile {
            get {
                return ResourceManager.GetString("Mobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to სამსახური.
        /// </summary>
        public static string Office {
            get {
                return ResourceManager.GetString("Office", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ოპერაცია წარმატებით შესრულდ.
        /// </summary>
        public static string OperationCompleted {
            get {
                return ResourceManager.GetString("OperationCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to სხვა.
        /// </summary>
        public static string Other {
            get {
                return ResourceManager.GetString("Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to პირადი ნომერი სავალდებულო ველია.
        /// </summary>
        public static string PersonalNumberIsRequred {
            get {
                return ResourceManager.GetString("PersonalNumberIsRequred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to პირადი ნომერი უნდა შეიცავდეს 11 -ციფრს.
        /// </summary>
        public static string PersonalNumberLengthRestrict {
            get {
                return ResourceManager.GetString("PersonalNumberLengthRestrict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to პირადი ნომერი უნდა შეიცავდეს მხოლოდ ციფრებს.
        /// </summary>
        public static string PersonalNumberRestrict {
            get {
                return ResourceManager.GetString("PersonalNumberRestrict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ფიზიკური პირი და მასთან დასაკავშირებელი ფიზიკური პირ ვერ მოძებნა.
        /// </summary>
        public static string PersonAndRelatedPersonNotFound {
            get {
                return ResourceManager.GetString("PersonAndRelatedPersonNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to პიროვნება მინიმუმ 18 წლის უნდა იყოს.
        /// </summary>
        public static string PersonBirthDateAgeRestrict {
            get {
                return ResourceManager.GetString("PersonBirthDateAgeRestrict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to დაბადების თარიღი სავალდებულო ველია.
        /// </summary>
        public static string PersonBirthDateIsRequred {
            get {
                return ResourceManager.GetString("PersonBirthDateIsRequred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ფიზიკური პირის სახელი სავალდებულო ველია.
        /// </summary>
        public static string PersonFnameIsRequred {
            get {
                return ResourceManager.GetString("PersonFnameIsRequred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to სახელი უნდა შეიცავდეს მაქსიმუმ 50 -სიმბოლოს.
        /// </summary>
        public static string PersonFnameMaxLengthRestrict {
            get {
                return ResourceManager.GetString("PersonFnameMaxLengthRestrict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to სახელი უნდა შეიცავდეს მინიმუმ 2 -სიმბოლოს.
        /// </summary>
        public static string PersonFnameMinLengthRestrict {
            get {
                return ResourceManager.GetString("PersonFnameMinLengthRestrict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to სახელი უნდა შეიცავდეს მხოლოდ ქართული ან ლათინური ანბანის ასოებს.
        /// </summary>
        public static string PersonFnameRestrict {
            get {
                return ResourceManager.GetString("PersonFnameRestrict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ფიზიკური პირის გვარი სავალდებულო ველია.
        /// </summary>
        public static string PersonLnameIsRequred {
            get {
                return ResourceManager.GetString("PersonLnameIsRequred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to გვარი უნდა შეიცავდეს მაქსიმუმ 50 -სიმბოლოს.
        /// </summary>
        public static string PersonLnameMaxLengthRestrict {
            get {
                return ResourceManager.GetString("PersonLnameMaxLengthRestrict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to გვარი უნდა შეიცავდეს მინიმუმ 2 -სიმბოლოს.
        /// </summary>
        public static string PersonLnameMinLengthRestrict {
            get {
                return ResourceManager.GetString("PersonLnameMinLengthRestrict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to გვარი უნდა შეიცავდეს მხოლოდ ქართული ან ლათინური ანბანის ასოებს.
        /// </summary>
        public static string PersonLnameRestrict {
            get {
                return ResourceManager.GetString("PersonLnameRestrict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ფიზიკური პირი ვერ მოიძებნა.
        /// </summary>
        public static string PersonNotFound {
            get {
                return ResourceManager.GetString("PersonNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ტელეფონი უნდა შეიცავდეს მაქსიმუმ 50 -სიმბოლოს.
        /// </summary>
        public static string PhoneNumberMaxLengthRestrict {
            get {
                return ResourceManager.GetString("PhoneNumberMaxLengthRestrict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ტელეფონი უნდა შეიცავდეს მინიმუმ 4 -სიმბოლოს.
        /// </summary>
        public static string PhoneNumberMinLengthRestrict {
            get {
                return ResourceManager.GetString("PhoneNumberMinLengthRestrict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ტელეფონის ტიპი არ არის სწორი (დასაშვები მნიშვნელობებია : Mobile, Office, Home ).
        /// </summary>
        public static string PhoneTypeEnumNotCorrect {
            get {
                return ResourceManager.GetString("PhoneTypeEnumNotCorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ფოთი.
        /// </summary>
        public static string Poti {
            get {
                return ResourceManager.GetString("Poti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to დასაკავშირებელი ფიზიკური პირი ვერ მოძებნა.
        /// </summary>
        public static string RelatedPersonNotFound {
            get {
                return ResourceManager.GetString("RelatedPersonNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ნათესავი.
        /// </summary>
        public static string Relative {
            get {
                return ResourceManager.GetString("Relative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to რუსთავი.
        /// </summary>
        public static string Rustavi {
            get {
                return ResourceManager.GetString("Rustavi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to სიღნაღი.
        /// </summary>
        public static string Sighnaghi {
            get {
                return ResourceManager.GetString("Sighnaghi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to თბილისი.
        /// </summary>
        public static string Tbilisi {
            get {
                return ResourceManager.GetString("Tbilisi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ზუგდიდი.
        /// </summary>
        public static string Zugdidi {
            get {
                return ResourceManager.GetString("Zugdidi", resourceCulture);
            }
        }
    }
}
